//! Chat session and message types for the conversation engine.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::entity::Entity;
use crate::memory::Memory;

/// Role of a message sender within a chat conversation.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum MessageRole {
    /// A message sent by the user.
    User,
    /// A message generated by the AI assistant.
    Assistant,
    /// A system-level instruction injected into the context.
    System,
    /// A tool call result injected by the runtime.
    Tool,
}

/// A single message within a chat session.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    /// Stable primary key.
    pub id: Uuid,
    /// The session this message belongs to.
    pub session_id: Uuid,
    /// Role of the message sender.
    pub role: MessageRole,
    /// Plain-text or markdown content of the message.
    pub content: String,
    /// Optional tool name (for `MessageRole::Tool` messages).
    pub tool_name: Option<String>,
    /// Optional raw tool call result JSON.
    pub tool_result: Option<serde_json::Value>,
    /// Token count estimate for context window tracking.
    pub token_count: Option<u32>,
    /// Message creation timestamp.
    pub created_at: DateTime<Utc>,
}

/// A conversation session grouping related messages.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatSession {
    /// Stable primary key.
    pub id: Uuid,
    /// Owner of this session.
    pub user_id: String,
    /// Optional human-readable label.
    pub title: Option<String>,
    /// All messages in this session, ordered by `created_at`.
    pub messages: Vec<ChatMessage>,
    /// Whether the session has been compressed (old messages summarised).
    pub is_compressed: bool,
    /// Session creation timestamp.
    pub created_at: DateTime<Utc>,
    /// Timestamp of the most recent message.
    pub updated_at: DateTime<Utc>,
}

/// The parsed structure of an LLM response that may include side effects.
///
/// The assistant is prompted to return JSON matching this schema so that
/// the runtime can atomically apply memory saves alongside the reply text.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StructuredResponse {
    /// The plain-text reply to surface to the user.
    pub reply: String,
    /// Zero or more new memories the LLM decided should be stored.
    pub memories_to_save: Vec<MemoryToSave>,
    /// Optional list of entity normalized values the response draws upon.
    /// The LLM returns normalized strings (e.g. "alice_smith"), not UUIDs.
    #[serde(default)]
    pub referenced_entities: Vec<String>,
    /// Tool calls the LLM is requesting the engine to execute before final reply.
    #[serde(default)]
    pub tool_calls: Vec<ToolCallRequest>,
}

/// A request from the LLM to execute a tool (in-band JSON tool calling).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ToolCallRequest {
    /// Tool name in snake_case (e.g. "get_calendar_events").
    pub name: String,
    /// Arguments to pass to the tool.
    #[serde(default)]
    pub arguments: serde_json::Value,
}

/// A memory the LLM is requesting be persisted.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MemoryToSave {
    /// Semantic category for storage and decay.
    ///
    /// Accepts both a plain string (`"reminder"`) and the map form the LLM
    /// sometimes emits (`{"Reminder": null}`).  Unknown values fall back to
    /// `MemoryCategory::General`.
    #[serde(deserialize_with = "deserialize_memory_category")]
    pub category: crate::memory::MemoryCategory,
    /// Human-readable content of the memory.
    pub content: String,
    /// Normalised entity values this memory relates to.
    #[serde(default)]
    pub related_entities: Vec<String>,
    /// Importance weight in `[0.0, 1.0]`.
    #[serde(
        default = "default_importance",
        deserialize_with = "deserialize_importance"
    )]
    pub importance: f32,
}

fn default_importance() -> f32 {
    0.5
}

fn deserialize_importance<'de, D: serde::Deserializer<'de>>(d: D) -> Result<f32, D::Error> {
    struct V;
    impl<'de> serde::de::Visitor<'de> for V {
        type Value = f32;
        fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
            write!(f, "a float, integer, or importance string")
        }
        fn visit_f64<E>(self, v: f64) -> Result<f32, E> {
            Ok(v as f32)
        }
        fn visit_i64<E>(self, v: i64) -> Result<f32, E> {
            Ok((v as f32).clamp(0.0, 1.0))
        }
        fn visit_u64<E>(self, v: u64) -> Result<f32, E> {
            Ok((v as f32).clamp(0.0, 1.0))
        }
        fn visit_str<E: serde::de::Error>(self, s: &str) -> Result<f32, E> {
            Ok(match s.to_lowercase().as_str() {
                "low" | "minor" => 0.2,
                "medium" | "normal" | "moderate" => 0.5,
                "high" | "important" => 0.8,
                "critical" | "very high" | "urgent" => 1.0,
                other => other.parse::<f32>().unwrap_or(0.5).clamp(0.0, 1.0),
            })
        }
        fn visit_none<E>(self) -> Result<f32, E> {
            Ok(0.5)
        }
        fn visit_unit<E>(self) -> Result<f32, E> {
            Ok(0.5)
        }
    }
    d.deserialize_any(V)
}

fn deserialize_memory_category<'de, D>(d: D) -> Result<crate::memory::MemoryCategory, D::Error>
where
    D: serde::Deserializer<'de>,
{
    use crate::memory::MemoryCategory;

    fn from_str(s: &str) -> MemoryCategory {
        match s.to_lowercase().as_str() {
            "user_preference" | "userpreference" | "preference" => MemoryCategory::UserPreference,
            "person_fact" | "personfact" => MemoryCategory::PersonFact,
            "project_fact" | "projectfact" => MemoryCategory::ProjectFact,
            "company_fact" | "companyfact" => MemoryCategory::CompanyFact,
            "recurring_event" | "recurringevent" => MemoryCategory::RecurringEvent,
            "decision" => MemoryCategory::Decision,
            "event" => MemoryCategory::Event,
            "reminder" => MemoryCategory::Reminder,
            "location" => MemoryCategory::Location,
            "contact" => MemoryCategory::Contact,
            _ => MemoryCategory::General,
        }
    }

    let v = serde_json::Value::deserialize(d)?;
    match &v {
        serde_json::Value::String(s) => Ok(from_str(s)),
        serde_json::Value::Object(map) => {
            // LLM sometimes emits {"Reminder": null} — treat first key as variant name.
            Ok(map
                .keys()
                .next()
                .map(|k| from_str(k))
                .unwrap_or(MemoryCategory::General))
        }
        _ => Ok(MemoryCategory::General),
    }
}

/// Context bundle assembled for each chat completion call.
#[derive(Debug, Clone)]
pub struct ChatContext {
    /// Memories retrieved by semantic similarity to the user's query.
    pub relevant_memories: Vec<Memory>,
    /// Entities retrieved from the knowledge graph.
    pub relevant_entities: Vec<Entity>,
    /// Summary of prior conversation if the session was compressed.
    pub session_summary: Option<String>,
}
