use serde::{Deserialize, Serialize};
use std::fmt::Write as FmtWrite;

#[derive(Debug, Deserialize, Serialize)]
#[serde(tag = "provider", rename_all = "lowercase")]
pub enum LlmConfig {
    Openrouter { api_key: String },
    Bedrock { region: String, model_id: String },
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(tag = "mode", rename_all = "lowercase")]
pub enum SlackConfig {
    #[serde(rename = "self")]
    SelfHosted {
        bot_token: String,
        app_token: String,
        user_token: Option<String>,
    },
    Managed {
        router_url: String,
    },
    Skip,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct SkillsConfig {
    pub metro_north: bool,
    pub imessage: bool,
    pub tavily: bool,
    pub tavily_api_key: Option<String>,
    pub slack_search: bool,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct InstallerConfig {
    pub llm: LlmConfig,
    pub slack: SlackConfig,
    pub google_email: Option<String>,
    pub skills: SkillsConfig,
}

#[tauri::command]
pub async fn write_config(config: InstallerConfig) -> Result<(), String> {
    let config_dir = dirs::home_dir()
        .ok_or("cannot find home directory")?
        .join(".config/trusty-izzie");

    tokio::fs::create_dir_all(&config_dir)
        .await
        .map_err(|e| e.to_string())?;

    let mut out = String::new();
    writeln!(out, "# Generated by Izzie Installer").ok();

    match &config.llm {
        LlmConfig::Openrouter { api_key } => {
            writeln!(out, "# LLM").ok();
            writeln!(out, "OPENROUTER_API_KEY={api_key}").ok();
        }
        LlmConfig::Bedrock { region, model_id } => {
            writeln!(out, "# LLM").ok();
            writeln!(out, "AWS_REGION={region}").ok();
            writeln!(out, "AWS_BEDROCK_MODEL_ID={model_id}").ok();
        }
    }

    if let Some(email) = &config.google_email {
        writeln!(out, "# Google").ok();
        writeln!(out, "TRUSTY_PRIMARY_EMAIL={email}").ok();
    }

    match &config.slack {
        SlackConfig::SelfHosted {
            bot_token,
            app_token,
            user_token,
        } => {
            writeln!(out, "# Slack").ok();
            writeln!(out, "SLACK_BOT_TOKEN={bot_token}").ok();
            writeln!(out, "SLACK_APP_TOKEN={app_token}").ok();
            if let Some(ut) = user_token {
                writeln!(out, "SLACK_USER_TOKEN={ut}").ok();
            }
        }
        SlackConfig::Managed { router_url } => {
            writeln!(out, "# Slack").ok();
            writeln!(out, "TRUSTY_ROUTER_URL={router_url}").ok();
        }
        SlackConfig::Skip => {}
    }

    let mut skills: Vec<&str> = vec![
        "web_search",
        "weather",
        "calendar",
        "email",
        "memory",
        "briefing",
    ];
    if config.skills.imessage {
        skills.push("imessage");
    }
    if config.skills.metro_north {
        skills.push("metro_north");
    }
    if config.skills.slack_search {
        skills.push("slack_search");
    }
    if config.skills.tavily {
        skills.push("tavily");
    }

    writeln!(out, "# Skills").ok();
    writeln!(out, "TRUSTY_SKILLS_ENABLED={}", skills.join(",")).ok();
    if config.skills.tavily {
        if let Some(key) = &config.skills.tavily_api_key {
            writeln!(out, "TAVILY_API_KEY={key}").ok();
        }
    }

    writeln!(out, "# Paths").ok();
    writeln!(out, "TRUSTY_DATA_DIR=~/.local/share/trusty-izzie").ok();

    let path = config_dir.join("config.env");
    tokio::fs::write(&path, out)
        .await
        .map_err(|e| e.to_string())?;

    Ok(())
}
