use serde::{Deserialize, Serialize};
use std::fmt::Write as FmtWrite;

fn store_secret(key: &str, value: &str) -> Result<(), String> {
    // Delete existing
    let _ = std::process::Command::new("security")
        .args(["delete-generic-password", "-s", "trusty-izzie", "-a", key])
        .output();
    // Add with allow-any-app ACL (-T "") so rebuilding never triggers a prompt
    let status = std::process::Command::new("security")
        .args([
            "add-generic-password",
            "-s",
            "trusty-izzie",
            "-a",
            key,
            "-w",
            value,
            "-T",
            "",
        ])
        .status()
        .map_err(|e| e.to_string())?;
    if status.success() {
        Ok(())
    } else {
        Err(format!("Failed to store {}", key))
    }
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(tag = "provider", rename_all = "lowercase")]
pub enum LlmConfig {
    Openrouter { api_key: String },
    Bedrock { region: String, model_id: String },
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(tag = "mode", rename_all = "lowercase")]
pub enum SlackConfig {
    #[serde(rename = "self")]
    SelfHosted {
        bot_token: String,
        app_token: String,
        user_token: Option<String>,
        webhook_url: Option<String>,
    },
    Managed {
        router_url: String,
        router_token: String,
        webhook_url: Option<String>,
    },
    Skip,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct SkillsConfig {
    /// List of enabled skill IDs (e.g. ["web_search","weather","metro_north"])
    pub enabled: Vec<String>,
    /// Map of env_var → value for skills that require API keys
    pub keys: std::collections::HashMap<String, String>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct InstallerConfig {
    pub llm: LlmConfig,
    pub slack: SlackConfig,
    pub google_email: Option<String>,
    pub skills: SkillsConfig,
}

#[tauri::command]
pub async fn write_config(config: InstallerConfig) -> Result<(), String> {
    let config_subdir = match crate::INSTANCE_ENV {
        "dev" => ".config/trusty-izzie-dev",
        _ => ".config/trusty-izzie",
    };
    let config_dir = dirs::home_dir()
        .ok_or("cannot find home directory")?
        .join(config_subdir);

    tokio::fs::create_dir_all(&config_dir)
        .await
        .map_err(|e| e.to_string())?;

    let mut out = String::new();
    writeln!(out, "# Generated by Izzie Installer").ok();
    writeln!(out, "TRUSTY_ENV={}", crate::INSTANCE_ENV).ok();

    // Store secrets in Keychain; log warnings but do not fail the install.
    match &config.llm {
        LlmConfig::Openrouter { api_key } => {
            if let Err(e) = store_secret("OPENROUTER_API_KEY", api_key) {
                eprintln!("warn: failed to store OPENROUTER_API_KEY in Keychain: {e}");
            }
            writeln!(out, "# LLM provider").ok();
            writeln!(out, "TRUSTY_LLM_PROVIDER=openrouter").ok();
        }
        LlmConfig::Bedrock { region, model_id } => {
            writeln!(out, "# LLM").ok();
            writeln!(out, "AWS_REGION={region}").ok();
            writeln!(out, "AWS_BEDROCK_MODEL_ID={model_id}").ok();
        }
    }

    if let Some(email) = &config.google_email {
        writeln!(out, "# Google").ok();
        writeln!(out, "TRUSTY_PRIMARY_EMAIL={email}").ok();
    }

    match &config.slack {
        SlackConfig::SelfHosted {
            bot_token,
            app_token,
            user_token,
            webhook_url,
        } => {
            if let Err(e) = store_secret("SLACK_BOT_TOKEN", bot_token) {
                eprintln!("warn: failed to store SLACK_BOT_TOKEN in Keychain: {e}");
            }
            if let Err(e) = store_secret("SLACK_APP_TOKEN", app_token) {
                eprintln!("warn: failed to store SLACK_APP_TOKEN in Keychain: {e}");
            }
            if let Some(ut) = user_token {
                if let Err(e) = store_secret("SLACK_USER_TOKEN", ut) {
                    eprintln!("warn: failed to store SLACK_USER_TOKEN in Keychain: {e}");
                }
            }
            if let Some(wu) = webhook_url {
                if !wu.is_empty() {
                    if let Err(e) = store_secret("SLACK_WEBHOOK_URL", wu) {
                        eprintln!("warn: failed to store SLACK_WEBHOOK_URL in Keychain: {e}");
                    }
                }
            }
            writeln!(out, "# Slack mode").ok();
            writeln!(out, "TRUSTY_SLACK_MODE=self").ok();
        }
        SlackConfig::Managed {
            router_url,
            router_token,
            webhook_url,
        } => {
            writeln!(out, "# Slack").ok();
            writeln!(out, "TRUSTY_ROUTER_URL={router_url}").ok();
            writeln!(out, "TRUSTY_ROUTER_TOKEN={router_token}").ok();
            if let Some(wu) = webhook_url {
                if !wu.is_empty() {
                    if let Err(e) = store_secret("SLACK_WEBHOOK_URL", wu) {
                        eprintln!("warn: failed to store SLACK_WEBHOOK_URL in Keychain: {e}");
                    }
                }
            }
        }
        SlackConfig::Skip => {}
    }

    writeln!(out, "# Skills").ok();
    writeln!(
        out,
        "TRUSTY_SKILLS_ENABLED={}",
        config.skills.enabled.join(",")
    )
    .ok();
    // Store skill API keys in Keychain; only write non-secret config to file
    let mut sorted_keys: Vec<(&String, &String)> = config.skills.keys.iter().collect();
    sorted_keys.sort_by_key(|(k, _)| *k);
    for (env, value) in &sorted_keys {
        if let Err(e) = store_secret(env, value) {
            eprintln!("warn: failed to store {env} in Keychain: {e}");
        }
    }

    writeln!(out, "# Paths").ok();
    writeln!(out, "TRUSTY_DATA_DIR=~/.local/share/trusty-izzie").ok();

    let path = config_dir.join("config.env");
    tokio::fs::write(&path, out)
        .await
        .map_err(|e| e.to_string())?;

    Ok(())
}
