use serde::{Deserialize, Serialize};
use std::fmt::Write as FmtWrite;

#[derive(Debug, Deserialize, Serialize)]
#[serde(tag = "provider", rename_all = "lowercase")]
pub enum LlmConfig {
    Openrouter { api_key: String },
    Bedrock { region: String, model_id: String },
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(tag = "mode", rename_all = "lowercase")]
pub enum SlackConfig {
    #[serde(rename = "self")]
    SelfHosted {
        bot_token: String,
        app_token: String,
        user_token: Option<String>,
    },
    Managed {
        router_url: String,
        router_token: String,
    },
    Skip,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct SkillsConfig {
    /// List of enabled skill IDs (e.g. ["web_search","weather","metro_north"])
    pub enabled: Vec<String>,
    /// Map of env_var → value for skills that require API keys
    pub keys: std::collections::HashMap<String, String>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct InstallerConfig {
    pub llm: LlmConfig,
    pub slack: SlackConfig,
    pub google_email: Option<String>,
    pub skills: SkillsConfig,
}

#[tauri::command]
pub async fn write_config(config: InstallerConfig) -> Result<(), String> {
    let config_dir = dirs::home_dir()
        .ok_or("cannot find home directory")?
        .join(".config/trusty-izzie");

    tokio::fs::create_dir_all(&config_dir)
        .await
        .map_err(|e| e.to_string())?;

    let mut out = String::new();
    writeln!(out, "# Generated by Izzie Installer").ok();

    match &config.llm {
        LlmConfig::Openrouter { api_key } => {
            writeln!(out, "# LLM").ok();
            writeln!(out, "OPENROUTER_API_KEY={api_key}").ok();
        }
        LlmConfig::Bedrock { region, model_id } => {
            writeln!(out, "# LLM").ok();
            writeln!(out, "AWS_REGION={region}").ok();
            writeln!(out, "AWS_BEDROCK_MODEL_ID={model_id}").ok();
        }
    }

    if let Some(email) = &config.google_email {
        writeln!(out, "# Google").ok();
        writeln!(out, "TRUSTY_PRIMARY_EMAIL={email}").ok();
    }

    match &config.slack {
        SlackConfig::SelfHosted {
            bot_token,
            app_token,
            user_token,
        } => {
            writeln!(out, "# Slack").ok();
            writeln!(out, "SLACK_BOT_TOKEN={bot_token}").ok();
            writeln!(out, "SLACK_APP_TOKEN={app_token}").ok();
            if let Some(ut) = user_token {
                writeln!(out, "SLACK_USER_TOKEN={ut}").ok();
            }
        }
        SlackConfig::Managed {
            router_url,
            router_token,
        } => {
            writeln!(out, "# Slack").ok();
            writeln!(out, "TRUSTY_ROUTER_URL={router_url}").ok();
            writeln!(out, "TRUSTY_ROUTER_TOKEN={router_token}").ok();
        }
        SlackConfig::Skip => {}
    }

    writeln!(out, "# Skills").ok();
    writeln!(
        out,
        "TRUSTY_SKILLS_ENABLED={}",
        config.skills.enabled.join(",")
    )
    .ok();
    // Write any API keys declared by enabled skills
    let mut sorted_keys: Vec<(&String, &String)> = config.skills.keys.iter().collect();
    sorted_keys.sort_by_key(|(k, _)| *k);
    for (env, value) in sorted_keys {
        writeln!(out, "{env}={value}").ok();
    }

    writeln!(out, "# Paths").ok();
    writeln!(out, "TRUSTY_DATA_DIR=~/.local/share/trusty-izzie").ok();

    let path = config_dir.join("config.env");
    tokio::fs::write(&path, out)
        .await
        .map_err(|e| e.to_string())?;

    Ok(())
}
